import Head from "next/head";
import MainPage from "../components/Home/MainPage";
export default function Home() {
    return (
        <div>
            <Head>
                <title>Ncheck Bio Attendance</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <MainPage />
        </div>
    );
}
